# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LightModels
                                 A QGIS plugin
 LightModels
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-25
        copyright            : (C) 2023 by LightModels
        email                : dvornikov_alesha@mail.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


from qgis.gui import QgisInterface

# noinspection PyPep8Naming
def classFactory(iface: QgisInterface):  # pylint: disable=invalid-name
    """Load Models class from file Models.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .light_models import LightModels
    return LightModels(iface)


from abc import ABC, abstractmethod

class ILightModel(ABC):
    
    @property
    @abstractmethod
    def iface(self) -> QgisInterface:
        pass
    
    @property
    @abstractmethod
    def plugin_dir(self) -> str:
        pass
