GRAVITY_MODEL_VAR_NAME = {
    'LAYER_CONSUMER': 0,
    'LAYER_SITE': 1,
    'FIELD_CONSUMER': 2,
    'FIELD_SITE': 3,
    'ALPHA': 4,
    'BETA': 5,
    'DISTANCE_LIMIT_METERS': 6,
}

CONFIG_VALIDATION_ERROR = {
    '': '',
}
